// <auto-generated />
using System;
using Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    partial class ContactsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("AppCore.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasDiscriminator<string>("ContactType").HasValue("Contact");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.Entities.CrmRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            Description = "System administrator",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            Description = "Sales manager",
                            Name = "SalesManager",
                            NormalizedName = "SALESMANAGER"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            Description = "Salesperson",
                            Name = "Salesperson",
                            NormalizedName = "SALESPERSON"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            Description = "Support agent",
                            Name = "SupportAgent",
                            NormalizedName = "SUPPORTAGENT"
                        },
                        new
                        {
                            Id = "55555555-5555-5555-5555-555555555555",
                            Description = "Read only user",
                            Name = "ReadOnly",
                            NormalizedName = "READONLY"
                        });
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.Entities.CrmUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11111111-AAAA-BBBB-CCCC-111111111111",
                            CreatedAt = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "admin@crm.local",
                            EmailConfirmed = true,
                            FirstName = "System",
                            FullName = "System Administrator",
                            LastName = "Administrator",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@CRM.LOCAL",
                            NormalizedUserName = "ADMIN@CRM.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEC61ZTRkkgM1/v8xX5/OnUVBzLUkn9jxtT4vsBT88zn2r1lc3eiBCv7JBR+/UmxaJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "admin@crm.local"
                        },
                        new
                        {
                            Id = "BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22222222-AAAA-BBBB-CCCC-222222222222",
                            CreatedAt = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Sales",
                            Email = "sales@crm.local",
                            EmailConfirmed = true,
                            FirstName = "Anna",
                            FullName = "Anna Sprzedaz",
                            LastName = "Sprzedaz",
                            LockoutEnabled = true,
                            NormalizedEmail = "SALES@CRM.LOCAL",
                            NormalizedUserName = "SALES@CRM.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEDhF7iyz2+8ISY6G82exZtcX19VSrIlH2d0xtubk9I+YRlrNxaOzf41Pcs32Mct0/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "BBBBBBBB-CCCC-DDDD-EEEE-FFFFFFFFFFFF",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "sales@crm.local"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA",
                            RoleId = "11111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            UserId = "BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB",
                            RoleId = "33333333-3333-3333-3333-333333333333"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppCore.Entities.Company", b =>
                {
                    b.HasBaseType("AppCore.Entities.Contact");

                    b.Property<decimal?>("AnnualRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KRS")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NIP")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("REGON")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasIndex("PrimaryContactId");

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("516a34d7-ccfb-4f20-85f3-62bd0f3af271"),
                            CreatedAt = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "biuro@wsei.edu.pl",
                            Phone = "123567123",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "edukacja",
                            Name = "WSEI",
                            Website = "https://wsei.edu.pl"
                        });
                });

            modelBuilder.Entity("AppCore.Entities.Organization", b =>
                {
                    b.HasBaseType("AppCore.Entities.Contact");

                    b.Property<string>("KRS")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mission")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasIndex("PrimaryContactId");

                    b.ToTable("Contact", t =>
                        {
                            t.Property("KRS")
                                .HasColumnName("Organization_KRS");

                            t.Property("Name")
                                .HasColumnName("Organization_Name");

                            t.Property("PrimaryContactId")
                                .HasColumnName("Organization_PrimaryContactId");

                            t.Property("Website")
                                .HasColumnName("Organization_Website");
                        });

                    b.HasDiscriminator().HasValue("Organization");
                });

            modelBuilder.Entity("AppCore.Entities.Person", b =>
                {
                    b.HasBaseType("AppCore.Entities.Contact");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasIndex("EmployerId");

                    b.HasIndex("OrganizationId");

                    b.HasDiscriminator().HasValue("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d54091d-abc8-49ec-9590-93ad3ed5458f"),
                            CreatedAt = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "adam@wsei.edu.pl",
                            Phone = "123456789",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            BirthDate = new DateTime(2001, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployerId = new Guid("516a34d7-ccfb-4f20-85f3-62bd0f3af271"),
                            FirstName = "Adam",
                            Gender = "Male",
                            LastName = "Nowak",
                            Position = "Programista"
                        },
                        new
                        {
                            Id = new Guid("b4dcb17c-f875-43f8-9d66-36597895a466"),
                            CreatedAt = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ewa@wsei.edu.pl",
                            Phone = "123123123",
                            Status = "Blocked",
                            UpdatedAt = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            BirthDate = new DateTime(2001, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployerId = new Guid("516a34d7-ccfb-4f20-85f3-62bd0f3af271"),
                            FirstName = "Ewa",
                            Gender = "Female",
                            LastName = "Kowalska",
                            Position = "Tester"
                        });
                });

            modelBuilder.Entity("AppCore.Entities.Contact", b =>
                {
                    b.OwnsOne("AppCore.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contact");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");

                            b1.HasData(
                                new
                                {
                                    ContactId = new Guid("3d54091d-abc8-49ec-9590-93ad3ed5458f"),
                                    City = "Kraków",
                                    Country = "Poland",
                                    PostalCode = "25-009",
                                    Street = "ul. Św. Filipa 17",
                                    Type = "Correspondence"
                                });
                        });

                    b.OwnsMany("AppCore.Entities.Note", "Notes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ContactId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ContactId");

                            b1.ToTable("ContactNotes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsMany("AppCore.Entities.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ContactId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ContactId");

                            b1.ToTable("ContactTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Notes");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Entities.Company", b =>
                {
                    b.HasOne("AppCore.Entities.Person", "PrimaryContact")
                        .WithMany()
                        .HasForeignKey("PrimaryContactId");

                    b.Navigation("PrimaryContact");
                });

            modelBuilder.Entity("AppCore.Entities.Organization", b =>
                {
                    b.HasOne("AppCore.Entities.Person", "PrimaryContact")
                        .WithMany()
                        .HasForeignKey("PrimaryContactId");

                    b.Navigation("PrimaryContact");
                });

            modelBuilder.Entity("AppCore.Entities.Person", b =>
                {
                    b.HasOne("AppCore.Entities.Company", "Employer")
                        .WithMany("Employees")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppCore.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AppCore.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AppCore.Entities.Organization", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
