@WebApi_HostAddress = http://localhost:5073

### GET all contacts
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json

### CREATE poprawny, id do kopiowania
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak",
  "email": "adam@wsei.edu.pl",
  "phone": "48 123 456 789",
  "birthDate": "1998-05-10",
  "gender": 0
}

### GET by existing id
GET {{WebApi_HostAddress}}/api/contacts/acc1348d-c9f0-436a-a456-d2ccc854d9a8
Accept: application/json

### GET by id non exising
GET {{WebApi_HostAddress}}/api/contacts/00000000-0000-0000-0000-000000000000
Accept: application/json


### CREATE contact blędny (test walidacji)
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "",
  "lastName": "Nowak"
}

### UPDATE exising conatc (wstaw id po stworzeniu)
PUT {{WebApi_HostAddress}}/api/contacts/7f802b2e-c745-42ed-843f-db9abf032dbb
Content-Type: application/json

{
  "firstName": "AdamUpdated",
  "email": "adam.updated@wsei.edu.pl"
}

###UPDATE non existing contact
PUT {{WebApi_HostAddress}}/api/contacts/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "firstName": "Ghost",
  "email": "ghost@wsei.edu.pl"
}

### Add note to existing person(skopiuj id notatki)

POST {{WebApi_HostAddress}}/api/contacts/acc1348d-c9f0-436a-a456-d2ccc854d9a8/notes
Content-Type: application/json

{
  "content": "New note"
}

### get note from existing contact

GET {{WebApi_HostAddress}}/api/contacts/acc1348d-c9f0-436a-a456-d2ccc854d9a8/notes
Accept: application/json

### delete existing note
DELETE {{WebApi_HostAddress}}/api/contacts/7f802b2e-c745-42ed-843f-db9abf032dbb/notes/fb3aa7b3-bfce-4c84-8a48-9ac582539292
Accept: application/json

### get note after delete
GET {{WebApi_HostAddress}}/api/contacts/7f802b2e-c745-42ed-843f-db9abf032dbb/notes
Accept: application/json

### add note to non existing contact
POST {{WebApi_HostAddress}}/api/contacts/00000000-0000-0000-0000-000000000000/notes
Content-Type: application/json

{
  "content": "Should fail"
}

### delete non existing note 
DELETE {{WebApi_HostAddress}}/api/contacts/7f802b2e-c745-42ed-843f-db9abf032dbb/notes/00000000-0000-0000-0000-000000000000
Accept: application/json

### new contact
POST http://localhost:5073/api/contacts
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "email": "jan.kowalski@wsei.edu.pl",
  "phone": "123456789",
  "birthDate": "2000-01-01",
  "gender": 0
}

### get all cont
GET http://localhost:5073/api/contacts
Accept: application/json

### DELETE contact
DELETE http://localhost:5073/api/contacts/d10c3b5c-9292-4a1b-9c3e-123456789abc
Accept: application/json

### create contact2
POST http://localhost:5073/api/contacts
Content-Type: application/json

{
  "firstName": "Anna",
  "lastName": "Zielińska",
  "email": "anna.zielinska@wsei.edu.pl",
  "phone": "500600700",
  "birthDate": "1999-04-15",
  "gender": 1
}