@WebApi_HostAddress = http://localhost:5073

### GET all contacts
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json

### CREATE poprawny
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak",
  "email": "adam@wsei.edu.pl",
  "phone": "48 123 456 789",
  "birthDate": "1998-05-10",
  "gender": 0
}

### GET by existing id
GET {{WebApi_HostAddress}}/api/contacts/acc1348d-c9f0-436a-a456-d2ccc854d9a8
Accept: application/json

### GET by id non exising
GET {{WebApi_HostAddress}}/api/contacts/00000000-0000-0000-0000-000000000000
Accept: application/json


### CREATE contact blędny (test walidacji)
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "",
  "lastName": "Nowak"
}

### UPDATE exising conatc (wstaw id po stworzeniu)
PUT {{WebApi_HostAddress}}/api/contacts/7f802b2e-c745-42ed-843f-db9abf032dbb
Content-Type: application/json

{
  "firstName": "AdamUpdated",
  "email": "adam.updated@wsei.edu.pl"
}

###UPDATE non existing contact
PUT {{WebApi_HostAddress}}/api/contacts/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "firstName": "Ghost",
  "email": "ghost@wsei.edu.pl"
}

### Add note to existing person(skopiuj id notatki)

POST {{WebApi_HostAddress}}/api/contacts/acc1348d-c9f0-436a-a456-d2ccc854d9a8/notes
Content-Type: application/json

{
  "content": "New note"
}

### get note from existing contact

GET {{WebApi_HostAddress}}/api/contacts/acc1348d-c9f0-436a-a456-d2ccc854d9a8/notes
Accept: application/json

### delete existing note
DELETE {{WebApi_HostAddress}}/api/contacts/7f802b2e-c745-42ed-843f-db9abf032dbb/notes/fb3aa7b3-bfce-4c84-8a48-9ac582539292
Accept: application/json

### get note after delete
GET {{WebApi_HostAddress}}/api/contacts/7f802b2e-c745-42ed-843f-db9abf032dbb/notes
Accept: application/json

### add note to non existing contact
POST {{WebApi_HostAddress}}/api/contacts/00000000-0000-0000-0000-000000000000/notes
Content-Type: application/json

{
  "content": "Should fail"
}

### delete non existing note 
DELETE {{WebApi_HostAddress}}/api/contacts/7f802b2e-c745-42ed-843f-db9abf032dbb/notes/00000000-0000-0000-0000-000000000000
Accept: application/json

### new contact
POST http://localhost:5073/api/contacts
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "email": "jan.kowalski@wsei.edu.pl",
  "phone": "123456789",
  "birthDate": "2000-01-01",
  "gender": 0
}

### get all cont
GET http://localhost:5073/api/contacts
Accept: application/json

### DELETE contact
DELETE http://localhost:5073/api/contacts/d10c3b5c-9292-4a1b-9c3e-123456789abc
Accept: application/json

### create contact2
POST http://localhost:5073/api/contacts
Content-Type: application/json

{
  "firstName": "Anna",
  "lastName": "Zielińska",
  "email": "anna.zielinska@wsei.edu.pl",
  "phone": "500600700",
  "birthDate": "1999-04-15",
  "gender": 1
}

### get contacts bez tokena
GET http://localhost:5073/api/contacts
Accept: application/json

### login
POST http://localhost:5073/api/auth/login
Content-Type: application/json

{
  "email": "sales@crm.local",
  "password": "Sales@123!"
}

### get contacts token
GET http://localhost:5073/api/contacts
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkJCQkJCQkJCLUJCQkItQkJCQi1CQkJCLUJCQkJCQkJCQkJCQiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNhbGVzQGNybS5sb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFubmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiU3ByemVkYXoiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiI1Zjk3OTE2Ny1jNDZlLTQ0NTgtOTY2YS1mNTU1ZmVhNTUyNzMiLCJpYXQiOiIxNzc2ODQ3NDIyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNwZXJzb24iLCJuYmYiOjE3NzY4NDc0MjIsImV4cCI6MTc3Njg1MTAyMiwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ._E1MkOV8si5g5gOQkPaWH0X1_3iULao9omWV6KN5IGQ


### ZADANIE FINALNE - POLIMORFICZNY KONTROLER KONTAKTÓW


### Logowanie
POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "sales@crm.local",
  "password": "Sales@123!"
}

### 2.Dodaj kontakt typu Person
POST {{WebApi_HostAddress}}/api/contacts/poly
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkJCQkJCQkJCLUJCQkItQkJCQi1CQkJCLUJCQkJCQkJCQkJCQiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNhbGVzQGNybS5sb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFubmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiU3ByemVkYXoiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiI5ZGVkODViMC1jNDAyLTRiYWQtYWI0Ni03Y2ViM2NiYWYwODYiLCJpYXQiOiIxNzgwMDQ0MjIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNwZXJzb24iLCJuYmYiOjE3ODAwNDQyMjAsImV4cCI6MTc4MDA0NzgyMCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.TQ74a7z3RfzfT3fqAyZGP-KbteFp3x1tZ34gjAJH95g

{
  "contactType": "Person",
  "firstName": "Jan",
  "lastName": "Kowalski",
  "email": "jan.kowalski@demo.pl",
  "phone": "48123456789",
  "gender": "Male",
  "position": "Dyrektor"
}

### 3.Dodaj kontakt typu Company
POST {{WebApi_HostAddress}}/api/contacts/poly
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkJCQkJCQkJCLUJCQkItQkJCQi1CQkJCLUJCQkJCQkJCQkJCQiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNhbGVzQGNybS5sb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFubmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiU3ByemVkYXoiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiI5ZGVkODViMC1jNDAyLTRiYWQtYWI0Ni03Y2ViM2NiYWYwODYiLCJpYXQiOiIxNzgwMDQ0MjIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNwZXJzb24iLCJuYmYiOjE3ODAwNDQyMjAsImV4cCI6MTc4MDA0NzgyMCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.TQ74a7z3RfzfT3fqAyZGP-KbteFp3x1tZ34gjAJH95g

{
  "contactType": "Company",
  "name": "Acme Corp",
  "email": "contact@acme.pl",
  "phone": "48123000000",
  "nip": "1234567890",
  "industry": "IT",
  "website": "https://acme.pl"
}

### 4.Dodaj kontakt typu Organization
POST {{WebApi_HostAddress}}/api/contacts/poly
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkJCQkJCQkJCLUJCQkItQkJCQi1CQkJCLUJCQkJCQkJCQkJCQiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNhbGVzQGNybS5sb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFubmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiU3ByemVkYXoiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiI5ZGVkODViMC1jNDAyLTRiYWQtYWI0Ni03Y2ViM2NiYWYwODYiLCJpYXQiOiIxNzgwMDQ0MjIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNwZXJzb24iLCJuYmYiOjE3ODAwNDQyMjAsImV4cCI6MTc4MDA0NzgyMCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.TQ74a7z3RfzfT3fqAyZGP-KbteFp3x1tZ34gjAJH95g

{
  "contactType": "Organization",
  "name": "Fundacja Przyszłość",
  "email": "info@fundacja.pl",
  "phone": "48100200300",
  "type": "Foundation",
  "mission": "Wspieranie edukacji dzieci."
}

### 5. Pobierz wszystkie kontakty (wymaga tokena)
GET {{WebApi_HostAddress}}/api/contacts/poly
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkJCQkJCQkJCLUJCQkItQkJCQi1CQkJCLUJCQkJCQkJCQkJCQiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNhbGVzQGNybS5sb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFubmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiU3ByemVkYXoiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiI5ZGVkODViMC1jNDAyLTRiYWQtYWI0Ni03Y2ViM2NiYWYwODYiLCJpYXQiOiIxNzgwMDQ0MjIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNwZXJzb24iLCJuYmYiOjE3ODAwNDQyMjAsImV4cCI6MTc4MDA0NzgyMCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.TQ74a7z3RfzfT3fqAyZGP-KbteFp3x1tZ34gjAJH95g

### 6. Pobierz kontakt bez tokena- oczekiwana 401
GET {{WebApi_HostAddress}}/api/contacts/poly

### 7. Pobierz kontakt po ID (id z pkt.2)
GET {{WebApi_HostAddress}}/api/contacts/poly/87c8725a-95ba-4335-bea6-2c9dc07001e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkJCQkJCQkJCLUJCQkItQkJCQi1CQkJCLUJCQkJCQkJCQkJCQiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNhbGVzQGNybS5sb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFubmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiU3ByemVkYXoiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiI5ZGVkODViMC1jNDAyLTRiYWQtYWI0Ni03Y2ViM2NiYWYwODYiLCJpYXQiOiIxNzgwMDQ0MjIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNwZXJzb24iLCJuYmYiOjE3ODAwNDQyMjAsImV4cCI6MTc4MDA0NzgyMCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.TQ74a7z3RfzfT3fqAyZGP-KbteFp3x1tZ34gjAJH95g

### 8. Edytuj kontakt (id z pkt.2)
PUT {{WebApi_HostAddress}}/api/contacts/poly/87c8725a-95ba-4335-bea6-2c9dc07001e5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkJCQkJCQkJCLUJCQkItQkJCQi1CQkJCLUJCQkJCQkJCQkJCQiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNhbGVzQGNybS5sb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFubmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiU3ByemVkYXoiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiI5ZGVkODViMC1jNDAyLTRiYWQtYWI0Ni03Y2ViM2NiYWYwODYiLCJpYXQiOiIxNzgwMDQ0MjIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNwZXJzb24iLCJuYmYiOjE3ODAwNDQyMjAsImV4cCI6MTc4MDA0NzgyMCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.TQ74a7z3RfzfT3fqAyZGP-KbteFp3x1tZ34gjAJH95g

{
  "contactType": "Person",
  "firstName": "Jan",
  "lastName": "Kowalski Updated",
  "email": "jan.updated@demo.pl",
  "phone": "48999999999",
  "gender": "Male",
  "position": "CEO"
}

### 9. Usuń kontakt (id z pkt.2)
DELETE {{WebApi_HostAddress}}/api/contacts/poly/87c8725a-95ba-4335-bea6-2c9dc07001e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkJCQkJCQkJCLUJCQkItQkJCQi1CQkJCLUJCQkJCQkJCQkJCQiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNhbGVzQGNybS5sb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFubmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiU3ByemVkYXoiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiI5ZGVkODViMC1jNDAyLTRiYWQtYWI0Ni03Y2ViM2NiYWYwODYiLCJpYXQiOiIxNzgwMDQ0MjIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNwZXJzb24iLCJuYmYiOjE3ODAwNDQyMjAsImV4cCI6MTc4MDA0NzgyMCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.TQ74a7z3RfzfT3fqAyZGP-KbteFp3x1tZ34gjAJH95g